version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: devdb
      MYSQL_ROOT_PASSWORD: devdb
      MYSQL_USER: devdb
      MYSQL_PASSWORD: devdb

volumes:
  my-db:
